'use strict';

var app= angular.module('aOne', [])

.controller('browseController', function($scope){

$scope.items = [{"ITEM_ID":8,"ITEM_TITLE":"Italian Antique Hand-Painted Porcelain Trinket Boxes","ITEM_DESC":"Antique hand-painted porcelain trinket boxes with hinged lids, purchased in 1985 at the Clignancourt Flea Market in Paris, mint condition, $75 each \n2 inch square with gilt floral design\n1.75 inch diameter says FORCE and SAGESSE\n\nSalmon Size 34 SNS Profeil cross country ski boots\n\nFit Karbu 130cm cross country skis\n\n70 cm cross country skis","ITEM_POST_DATE":"2015-07-09T20:29:43.000Z","ITEM_POSTED_BY":6,"ITEM_BOUGHT_BY":null,"USER_GRAVATAR":"https://www.gravatar.com/avatar/0f4b2c92f1b04f9083caf68dbbc4cbe9.jpg?d=identicon","ITEM_PRICE":70,"ITEM_STATUS":"cancelled"},
{"ITEM_ID":2,"ITEM_TITLE":"Pool tables, 1\" Slate, Real Wood, NO MDF","ITEM_DESC":"Key Features:\nTable Size: 7' and 8' regulation sizes\nFrame: 100% Real Wood (NO Plywood, MDF or OSB)\nLegs: 100% Real Wood (NO Plywood, MDF or OSB)\nRails: 100% Real Wood (NO Plywood, MDF or OSB)\nSide 100% Real Wood (NO Plywood, MDF or OSB)\nSlate: 1\" Slate, Diamond Honed, Matched (Solid Wood Backed) \nPocket Size: Meets BCA Specifications\nPockets: 100% Leather (NO SYNTHETIC)\nRail Sights: Mother Pearl\nCushions: 100% Gum Cushions K66 (No Fillers)\nFelt: 21oz Felt (Upgrade to Championship)\nTable Guarantee: 5 year Manufacture Warranty (See web site for details)\nInstallation Guarantee: No payment due until you are 100% happy with the table.","ITEM_POST_DATE":"2015-07-09T20:45:11.999Z","ITEM_POSTED_BY":4,"ITEM_BOUGHT_BY":null,"USER_GRAVATAR":"https://www.gravatar.com/avatar/1cb1c39857f5eef49897f849251861a9.jpg?d=identicon","ITEM_PRICE":1450,"ITEM_STATUS":"available"},
{"ITEM_ID":3,"ITEM_TITLE":"2 pack tennis rackets","ITEM_DESC":"got some tennis rackets but they were not at a professional standard. still at great quality and awesome for anyone who wants to start playing tennis","ITEM_POST_DATE":"2015-07-09T20:50:24.999Z","ITEM_POSTED_BY":4,"ITEM_BOUGHT_BY":null,"USER_GRAVATAR":"https://www.gravatar.com/avatar/1cb1c39857f5eef49897f849251861a9.jpg?d=identicon","ITEM_PRICE":50,"ITEM_STATUS":"sold"},
{"ITEM_ID":21,"ITEM_TITLE":"Pool table","ITEM_DESC":"My pool table for sale","ITEM_POST_DATE":"2015-07-12T04:57:28.000Z","ITEM_POSTED_BY":4,"ITEM_BOUGHT_BY":null,"USER_GRAVATAR":"https://www.gravatar.com/avatar/1cb1c39857f5eef49897f849251861a9.jpg?d=identicon","ITEM_PRICE":100,"ITEM_STATUS":"sold"},
{"ITEM_ID":22,"ITEM_TITLE":"Used macbook","ITEM_DESC":"MBP 15 in retina 2012 model in great condition","ITEM_POST_DATE":"2015-07-12T15:40:12.000Z","ITEM_POSTED_BY":7,"ITEM_BOUGHT_BY":null,"USER_GRAVATAR":"https://www.gravatar.com/avatar/9e21e946f4d5e27400d1e54a0d8d9285.jpg?d=identicon","ITEM_PRICE":1650,"ITEM_STATUS":"available"},
{"ITEM_ID":61,"ITEM_TITLE":"Bicycle","ITEM_DESC":"My Schwinn Bike is ready to go","ITEM_POST_DATE":"2015-08-04T17:59:48.000Z","ITEM_POSTED_BY":81,"ITEM_BOUGHT_BY":null,"USER_GRAVATAR":"https://www.gravatar.com/avatar/b7636af5fbc1f3de6a60600c70156907.jpg?d=identicon","ITEM_PRICE":100,"ITEM_STATUS":"sold"},
{"ITEM_ID":7,"ITEM_TITLE":"White Alabaster Egg (mint condition)","ITEM_DESC":"White alabaster egg, approximately 3 inches long, mint condition, $5\n\nSalmon Size 34 SNS Profeil cross country ski boots\n\nFit Karbu 130cm cross country skis\n\n70 cm cross country skis","ITEM_POST_DATE":"2015-07-09T20:30:16.000Z","ITEM_POSTED_BY":5,"ITEM_BOUGHT_BY":null,"USER_GRAVATAR":"https://www.gravatar.com/avatar/64b5cefbdbbbb10b091774a15368db2d.jpg?d=identicon","ITEM_PRICE":5,"ITEM_STATUS":"available"},
{"ITEM_ID":9,"ITEM_TITLE":"Garden Tool Organizer / Bicycle Storage Rack - 36\"","ITEM_DESC":"Are you tired of tripping over a bunch of loose garden tools in your garage? Are your brooms, rakes, shovels, bicycles etc. always in a big cluttered mess? As a machine shop owner, I make a really nice, possibly the best, Garage Organizer - Garden Tool - Bicycle Storage Rack, where you can neatly hang these items.\n\n**** My Design:\n\n* Is very strong and holds many clumsy things, like garden tools and bicycles, in a tight place. \n* Is a very simple design, adjustable to fit many different items. \n* Doesn't take up any valuable floor space.\n* Bicycles can be hung parallel or perpendicular to the wall.\n* Includes many large Straight Hooks and two styles of Rubber Padded Bicycle Hook.\n* Long, tempered, Torx wood screws that will line up with every wall stud, with or without sheetrock.\n* Made from solid aluminum bar stock, threaded steel rod, nuts, washers, high quality tempered steel wood screws and machined aluminum screw adapters. \n* Includes a magnet to find wall studs, a Torx screw bit, eye screws for the ends of your wooden tool \nhandles, and easy instructions.\n\n**** Here's what you will receive: \n\n36\" Tool Rack Kit - $89.00\n* One 36\" aluminum beam with 36 threaded holes \n* Six 12\" hooks with nuts and washers \n* Four 8\" hooks with nuts and washers\n* Two styles of Rubber Padded Bicycle Hook with nuts and washers \n* Four 2 1/2\" wood screws with adapters\n* One Torx bit to fit the wood screws\n* One stud finder magnet\n* Six eye screws\n* Instructions\n\n$89.00 is a cash price for Santa Clara pick up. Reply with your phone number. \nI have this and 2 other larger sizes, extra hooks, more pictures, and better description on eBay.\nDo an eBay search for item # 161667038684\n\nSalmon Size 34 SNS Profeil cross country ski boots\n\nFit Karbu 130cm cross country skis\n\n70 cm cross country skis","ITEM_POST_DATE":"2015-07-09T20:31:19.000Z","ITEM_POSTED_BY":7,"ITEM_BOUGHT_BY":null,"USER_GRAVATAR":"https://www.gravatar.com/avatar/9e21e946f4d5e27400d1e54a0d8d9285.jpg?d=identicon","ITEM_PRICE":89,"ITEM_STATUS":"available"},
{"ITEM_ID":10,"ITEM_TITLE":"***2004 Yamaha R6 Motorcycle*** clean title***","ITEM_DESC":"For sale a clean 2004 Yamaha R6 factory blue with 27k commuting miles. Clean title in hand and current registration. Excellent condition. A few minor mods liked front signals, rear eliminator kit, integrated taillight, a rear solo seat cowl and frame sliders. All service up to date. Nothing is needed.\n\n\nprice: $3600 firm \nemail if interested and I will call you back asap. thx.\n\nSalmon Size 34 SNS Profeil cross country ski boots\n\nFit Karbu 130cm cross country skis\n\n70 cm cross country skis","ITEM_POST_DATE":"2015-07-09T20:31:08.000Z","ITEM_POSTED_BY":8,"ITEM_BOUGHT_BY":null,"USER_GRAVATAR":"https://www.gravatar.com/avatar/2d880fb7b80033f441dc142e111326d2.jpg?d=identicon","ITEM_PRICE":3600,"ITEM_STATUS":"sold"},
{"ITEM_ID":12,"ITEM_TITLE":"VOX Standard 24 Guitar- Made in Japan","ITEM_DESC":"This is a Vox Standard 24 3503, made some time between 1979 and 82. It works great and holds it's tuning, but it shows its wear. Consistent with it's age, this guitar has lots of dings, impressions, edge chipping, scratches and swirling (Pictures provided). \nA workhorse.\nI love it, but I am changing my sound. \nI have owned this VOX for about five years and it has been my personal electric guitar at the studio, a non smoker environment.\n\nThe serial number is 2010313. These were manufactured in Japan at the Matsumoku factory during the golden era of Japanese guitars. \n\nThe frets are in good condition, showing light wear. \n\nThe Dimarzio Super Distortion Humbuckers make this machine very powerful, crunchy and aggressive in a very \"1970's\" Classic or Glam rock kind of way. \n\nAdditional specs:\nStandard 24 Black - 3503\nBlack polyester finish\n24 3/4 inch scale length\nFixed neck construction; twinDiMarzio\nSuper Distortion Humbuckers\nBody and neck from selected Nato timber\nIndividual smooth machine heads\nVolume and tone controls for each pickup\nThree way pickup selector\n\nIncluded is a case that fits the Vox perfectly. It looks used on the outside, but it is a tank. The locks show some rust, but they work perfectly. I mean, these lock precisely AND the case comes with it's original key. The case lid opens to just past 90 degrees and stays there. The lines are straight and solid. I originally wanted to keep it, but it fits the Vox perfectly and matches it's age and quality of build so I am selling them together. \nLocal pick up only. Price is FIRM. Cash only and you must bring your own amp to test it so you know what it sounds like though something you already know. Right?\nSalmon Size 34 SNS Profeil cross country ski boots\n\nFit Karbu 130cm cross country skis\n\n70 cm cross country skis","ITEM_POST_DATE":"2015-07-09T20:30:42.999Z","ITEM_POSTED_BY":10,"ITEM_BOUGHT_BY":null,"USER_GRAVATAR":"https://www.gravatar.com/avatar/6a176042a73df72b4fe504dec322dd52.jpg?d=identicon","ITEM_PRICE":500,"ITEM_STATUS":"available"},
{"ITEM_ID":5,"ITEM_TITLE":"Kinetic by Kurt Road Machine Indoor Bicycle Trainer","ITEM_DESC":"Kinetic by Kurt Road Machine Indoor Bicycle Trainer and front wheel stand.\n\nUsed 2 times for about 30 mins each time. \n\nRetail price is $379.\n\nI am also selling the pictured Giant OCRc2 if interested.","ITEM_POST_DATE":"2015-07-09T20:31:36.999Z","ITEM_POSTED_BY":1,"ITEM_BOUGHT_BY":null,"USER_GRAVATAR":"https://www.gravatar.com/avatar/f2adf4eb7c402614b43ec15042fcbe49.jpg?d=identicon","ITEM_PRICE":200,"ITEM_STATUS":"sold"},
{"ITEM_ID":6,"ITEM_TITLE":"Cross Country Ski Boots and Skis","ITEM_DESC":"Kinetic by Kurt Road Machine Indoor Bicycle Trainer and rear wheel stand.\n\nUsed 2 times for about 30 mins each time. \n\nRetail price is $379.\n\nSalmon Size 34 SNS Profeil cross country ski boots\n\nFit Karbu 130cm cross country skis\n\n70 cm cross country skis","ITEM_POST_DATE":"2015-07-09T20:31:44.000Z","ITEM_POSTED_BY":4,"ITEM_BOUGHT_BY":null,"USER_GRAVATAR":"https://www.gravatar.com/avatar/1cb1c39857f5eef49897f849251861a9.jpg?d=identicon","ITEM_PRICE":20,"ITEM_STATUS":"available"},
{"ITEM_ID":11,"ITEM_TITLE":"1940's Noritake Japan China Set","ITEM_DESC":"1940's Noritake Japan China Set\nLynns of Alameda\n2807 Encinal Ave.\nAlameda\n\nSalmon Size 34 SNS Profeil cross country ski boots\n\nFit Karbu 130cm cross country skis\n\n70 cm cross country skis","ITEM_POST_DATE":"2015-07-09T20:32:03.999Z","ITEM_POSTED_BY":9,"ITEM_BOUGHT_BY":null,"USER_GRAVATAR":"https://www.gravatar.com/avatar/18829e0fbe77369f07afb60688aae1d0.jpg?d=identicon","ITEM_PRICE":150,"ITEM_STATUS":"sold"},
{"ITEM_ID":41,"ITEM_TITLE":"Samsung galaxy s6 active","ITEM_DESC":"I'm trying to sell or trade my galaxy s5 active, I would trade for a video game system or I would just sell it straight out. Serious inquiries only.","ITEM_POST_DATE":"2015-07-13T02:46:33.999Z","ITEM_POSTED_BY":12,"ITEM_BOUGHT_BY":null,"USER_GRAVATAR":"https://www.gravatar.com/avatar/64b5cefbdbbbb10b091774a15368db2d.jpg?d=identicon","ITEM_PRICE":255,"ITEM_STATUS":"sold"},
{"ITEM_ID":81,"ITEM_TITLE":"hello","ITEM_DESC":"hello world","ITEM_POST_DATE":"2015-08-14T00:10:55.000Z","ITEM_POSTED_BY":6,"ITEM_BOUGHT_BY":null,"USER_GRAVATAR":"https://www.gravatar.com/avatar/0f4b2c92f1b04f9083caf68dbbc4cbe9.jpg?d=identicon","ITEM_PRICE":50,"ITEM_STATUS":"available"},
{"ITEM_ID":4,"ITEM_TITLE":"unboxed iphone 6","ITEM_DESC":"Recd it as a birthday gift from my uncle but I already have a phone so don't need this. Unboxed with recpt","ITEM_POST_DATE":"2015-07-09T20:32:12.000Z","ITEM_POSTED_BY":3,"ITEM_BOUGHT_BY":null,"USER_GRAVATAR":"https://www.gravatar.com/avatar/8797f39d02e570e5ebbb04f74d8c13f2.jpg?d=identicon","ITEM_PRICE":600,"ITEM_STATUS":"available"},
{"ITEM_ID":13,"ITEM_TITLE":"Guitar","ITEM_DESC":"My used guitar","ITEM_POST_DATE":"2015-07-09T20:31:57.000Z","ITEM_POSTED_BY":11,"ITEM_BOUGHT_BY":null,"USER_GRAVATAR":"https://www.gravatar.com/avatar/5e93f7e9a7d0eb976722076e5a34ebee.jpg?d=identicon","ITEM_PRICE":100,"ITEM_STATUS":"available"},
{"ITEM_ID":1,"ITEM_TITLE":"2015 Star 36v golf cart...barely used","ITEM_DESC":"Features include:\nStreet legal light kit which includes- head and tail lights, turn signals, brake lights, horn, and hazards\nTinted folding windshield\nFolding side mirrors\n10??? polished aluminum wheels\nLow / high speed switch (runs up to 20 mph in high)\nBattery state of charge meter\nSide panels\nBack seat that folds to diamond plate flat bed\nRear safety grab bar","ITEM_POST_DATE":"2015-07-09T20:30:57.000Z","ITEM_POSTED_BY":2,"ITEM_BOUGHT_BY":null,"USER_GRAVATAR":"https://www.gravatar.com/avatar/c705cc9a8de9f669db8afb3bb825d70a.jpg?d=identicon","ITEM_PRICE":5650,"ITEM_STATUS":"available"},
{"ITEM_ID":82,"ITEM_TITLE":"hello","ITEM_DESC":"hello world","ITEM_POST_DATE":"2015-08-14T00:17:25.000Z","ITEM_POSTED_BY":6,"ITEM_BOUGHT_BY":null,"USER_GRAVATAR":"https://www.gravatar.com/avatar/0f4b2c92f1b04f9083caf68dbbc4cbe9.jpg?d=identicon","ITEM_PRICE":50,"ITEM_STATUS":"available"}]


});


