CREATE USER demouser IDENTIFIED BY Welcome1# 
DEFAULT TABLESPACE users
QUOTA UNLIMITED ON users;
CREATE ROLE node_role;
GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE VIEW, CREATE TRIGGER to node_role;
GRANT node_role TO demouser;

CREATE USER devuser IDENTIFIED BY Welcome1# 
DEFAULT TABLESPACE users
QUOTA UNLIMITED ON users;
GRANT node_role TO devuser;